### ISSUE TITLE
UML Diagram Updates

### ISSUE THREAD

**Issue by StevenH0824** [StevenH0824/Residential-Building-Management-System#16]
we have the updated diagram for our project. We need to focus on implementing these changes to the code base.

![Image](https://github.com/user-attachments/assets/876155cb-ec71-4f04-bd6b-2a235277cb7c)

**Comment by kimetn** [comment]
![new uml](https://github.com/user-attachments/assets/445d1e2f-233f-40c7-9d16-86a50d3cdae6)

Updated UML

**Comment by kimetn** [comment]
Current entities and Dto classes will be updated to reflect these changes.
